pipeline {
    agent any

    environment {
        IMAGE_NAME = "bkkrish007/spotify-devops"
        EC2_IP = "13.200.246.186"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Application') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest -f docker/Dockerfile .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "
                    docker stop spotify || true &&
                    docker rm spotify || true &&
                    docker pull $IMAGE_NAME:latest &&
                    docker run -d -p 8081:80 --name spotify $IMAGE_NAME:latest
                "
                '''
            }
        }
    }
}