pipeline {
    agent any

    stages {

        stage('Install & Build (Node Container)') {
            agent {
                docker {
                    image 'node:18'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t spotify-clone -f docker/Dockerfile .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                sh '''
                docker tag spotify-clone bkkrish007/spotify-devops:latest
                docker push bkkrish007/spotify-devops:latest
                '''
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@13.200.246.186 "
                docker stop spotify || true &&
                docker rm spotify || true &&
                docker pull bkkrish007/spotify-devops:latest &&
                docker run -d -p 8081:80 --name spotify bkkrish007/spotify-devops:latest
                "
                '''
            }
        }
    }
}